inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - test/**/*
    - db/**/*
    - Rakefile
    - ./*.gemspec

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 85

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  IndentationWidth: 2

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "lib/jekyll_openmoji/plugin.rb"

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 25

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MutableConstant:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/StringLiterals:
  EnforcedStyle: double_quotes
