#!/bin/bash
# Usage: script/release
#
# 1. Checks if tests pass,
# 2. commits gemspec,
# 3. tags the release with the version in the gemspec,
# 4. pushes "negarmoji" gem to RubyGems.org.

set -e

if git diff --quiet lib/jekyll-openmoji/version.rb; then
  echo "You must bump the version in the lib/jekyll-openmoji/version.rb first." >&2
  exit 1
fi

script/ci-build

version="$(gem build jekyll-openmoji.gemspec | awk '/Version:/ { print $2 }')"
git commit lib/jekyll-openmoji/version.rb -m "jekyll-openmoji $version"
git tag "v${version}"
git push origin HEAD "v${version}"
git push github HEAD "v${version}"
gem push "jekyll-openmoji-${version}.gem"